# サイトの設定
title: My Awesome Website
description: This is an example website.
theme: jekyll-theme-minimal

# ビルド設定
markdown: kramdown
permalink: pretty

# ソーシャルメディアリンク
social:
  - name: Twitter
    url: https://twitter.com/example
  - name: GitHub
    url: https://github.com/example

# ナビゲーションメニュー
navbar:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Blog
    url: /blog

# プラグインの設定
plugins:
  - jekyll-sitemap
  - jekyll-feed

# カスタム変数
custom_variable: custom_value
